

pool:
  name: 'Dev'
  agents:
  - name: 'eks-preprod'
# Nombre del pipeline
name: Docker Image Build and Push

# Variables de entorno
variables:
  AWS_ACCESS_KEY_ID: 'AKIA5VJLYRITMXVVFLVS'
  AWS_SECRET_ACCESS_KEY: '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'

# Pasos del pipeline
steps:
  # Construir la imagen de Docker
  - script: |
      docker build -t devops .

  # Autenticarse en ECR
  - script: |
      aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 939079010854.dkr.ecr.us-east-1.amazonaws.com

  # Subir la imagen de Docker a ECR
  - script: |
      docker tag devops:latest 939079010854.dkr.ecr.us-east-1.amazonaws.com/devops:latest
      docker push 939079010854.dkr.ecr.us-east-1.amazonaws.com/devops:latest

  # Borrar la imagen de Docker
  - script: |
      docker rmi my-image:latest

