# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

pool:
  name: 'Dev'
  agents:
   - name: 'eks-preprod'

jobs:
- job: Build
  displayName: Build on Ubuntu
  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install -y maven
      mvn clean package -DskipTests
      hostname


