pool:
  name: 'Dev'
  agents:
  - name: 'eks-preprod'

variables:
  AWS_ACCESS_KEY_ID: AKIA5VJLYRITMXVVFLVS
  AWS_SECRET_ACCESS_KEY: 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
  AWS_DEFAULT_REGION: us-east-1


steps:

  - script: |
        mvn clean package -DskipTests
        if [[ $? -ne 0 ]]; then
          echo "error mvn clean package -DskipTests"
          exit 1
        fi

        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        if [[ $? -ne 0 ]]; then
          echo "error aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID "
          exit 1
        fi

        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        if [[ $? -ne 0 ]]; then
          echo "error aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY"
          exit 1
        fi   

        aws configure set default.region $AWS_DEFAULT_REGION
        if [[ $? -ne 0 ]]; then
          echo "error aws configure set default.region $AWS_DEFAULT_REGION"
          exit 1
        fi 

        docker build -t devops .
        if [[ $? -ne 0 ]]; then
          echo "error docker build -t devops ."
          exit 1
        fi               
        
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 939079010854.dkr.ecr.us-east-1.amazonaws.com
        if [[ $? -ne 0 ]]; then
          echo "error aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 939079010854.dkr.ecr.us-east-1.amazonaws.com"
          exit 1
        fi        
                
        docker tag devops:latest 939079010854.dkr.ecr.us-east-1.amazonaws.com/devops:$(Build.BuildNumber)
        if [[ $? -ne 0 ]]; then
          echo "error docker tag devops:latest 939079010854.dkr.ecr.us-east-1.amazonaws.com/devops:$(Build.BuildNumber)"
          exit 1
        fi  

        docker push 939079010854.dkr.ecr.us-east-1.amazonaws.com/devops:$(Build.BuildNumber)
        if [[ $? -ne 0 ]]; then
          echo "error docker tag devops:latest 939079010854.dkr.ecr.us-east-1.amazonaws.com/devops:$(Build.BuildNumber)"
          exit 1
        fi                         

        docker rmi devops:latest                  
        if [[ $? -ne 0 ]]; then
          echo "error  docker rmi devops:latest"
          exit 1
        fi  
        
        sudo sed -i '26c\image:         devops:$(Build.BuildNumber)' ~/docker_book/manifiestos/deploy-rest-service.yaml
        if [[ $? -ne 0 ]]; then
          echo "error en el comando sed"
          exit 1
        fi 

        kubectl apply -f ~/docker_book/manifiestos/deploy-rest-service.yaml
        if [[ $? -ne 0 ]]; then
          echo "error en el comando kubectl"
          exit 1
        fi 


