

pool:
  name: 'Dev'
  agents:
  - name: 'eks-preprod'
# Nombre del pipeline
name: Docker Image Build and Push

# Variables de entorno
variables:
  AWS_ACCESS_KEY_ID: 'AKIA5VJLYRITMXVVFLVS'
  AWS_SECRET_ACCESS_KEY: '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'
  AWS_DEFAULT_REGION: 'us-east-1'

# Pasos del pipeline
steps:
 # Configurar Credenciales
  - script: |
      echo "$AWS_ACCESS_KEY_ID\n$AWS_SECRET_ACCESS_KEY" > aws-credentials
      export AWS_SHARED_CREDENTIALS_FILE=$(pwd)/aws-credentials
      aws configure set default.region $AWS_DEFAULT_REGION
    
  # Construir la imagen de Docker
  - script: |
      docker build -t devops .
      
  # Autenticarse en ECR
  - script: |
      aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

  # Subir la imagen de Docker a ECR
  - script: |
      docker tag devops:latest 939079010854.dkr.ecr.us-east-1.amazonaws.com/devops:latest
      docker push 939079010854.dkr.ecr.us-east-1.amazonaws.com/devops:latest

  # Borrar la imagen de Docker
  - script: |
      docker rmi my-image:latest

