

pool:
  name: 'Dev'
  agents:
   - name: 'eks-preprod'

  stages:
  - build
  - deploy
  - cleanup

variables:
  DOCKER_IMAGE_TAG: devops
  AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
  #AWS_REGION: us-east-1

  build:
    stage: build
    image: docker:latest
    script:
      - docker build -t $DOCKER_IMAGE_TAG .
    artifacts:
      paths:
        - Dockerfile

  deploy:
    stage: deploy
    image: docker:latest
    script:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 939079010854.dkr.ecr.us-east-1.amazonaws.com
      - docker docker tag devops:latest 939079010854.dkr.ecr.us-east-1.amazonaws.com/devops:latest
      - docker push 939079010854.dkr.ecr.us-east-1.amazonaws.com/devops:latest

  cleanup:
    stage: cleanup
    image: ubuntu:latest
    script:
      - docker rmi $DOCKER_IMAGE_TAG

