pool:
  name: 'Dev'
  agents:
  - name: 'eks-preprod'

variables:
  AWS_ACCESS_KEY_ID: AKIA5VJLYRITMXVVFLVS
  AWS_SECRET_ACCESS_KEY: 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
  AWS_DEFAULT_REGION: us-east-1
  

steps:

  - script: |
          mvn clean package -DskipTests
          salida=$(echo $?)
          if [[ $salida -eq 0 ]]; then
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            salida=$(echo $?)
            if [[ $salida -eq 0 ]]; then
              aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
              salida=$(echo $?)
              if [[ $salida -eq 0 ]]; then
                aws configure set default.region $AWS_DEFAULT_REGION
                salida=$(echo $?)
                if [[ $salida -eq 0 ]]; then
                docker build -t devops .
                  salida=$(echo $?)
                  if [[ $salida -eq 0 ]]; then
                  aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 939079010854.dkr.ecr.us-east-1.amazonaws.com
                    salida=$(echo $?)
                    if [[ $salida -eq 0 ]]; then
                      docker tag devops:latest 939079010854.dkr.ecr.us-east-1.amazonaws.com/devops:latest
                      salida=$(echo $?)
                      if [[ $salida -eq 0 ]]; then
                        docker push 939079010854.dkr.ecr.us-east-1.amazonaws.com/devops:latest
                        salida=$(echo $?)
                        if [[ $salida -eq 0 ]]; then
                          docker rmi devops:latest
                        else
                          echo "Uno o más comandos fallaron. Deteniendo la ejecución."
                        fi
                        exit 1
                      else
                        echo "Uno o más comandos fallaron. Deteniendo la ejecución."
                      fi
                      exit 1
                    else
                      echo "Uno o más comandos fallaron. Deteniendo la ejecución."
                    fi
                    exit 1
                  else
                    echo "Uno o más comandos fallaron. Deteniendo la ejecución."
                  fi
                  exit 1
                else
                  echo "Uno o más comandos fallaron. Deteniendo la ejecución."
                fi
                exit 1
              else
              echo "Uno o más comandos fallaron. Deteniendo la ejecución."
              fi
              exit 1
            else
              echo "Uno o más comandos fallaron. Deteniendo la ejecución."
            fi
            exit 1
           else
            echo "Uno o más comandos fallaron. Deteniendo la ejecución."
          fi
          exit 1


