apiVersion: v1
data:
  application.properties: |-
    spring.datasource.url=jdbc:postgresql://svc-db:5432/docker_book
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.datasource.username=book
    spring.datasource.password=book
    logging.level.org.springframework.web: DEBUG
    logging.level.org.hibernate: ERROR
kind: ConfigMap
metadata:
  creationTimestamp: null
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:application.properties: {}
    manager: kubectl
    operation: Update
    time: "2020-07-01T06:34:15Z"
  name: rest-service
  namespace: docker-book