apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: service-rest
  name: service-rest
  namespace: docker-book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-rest
  template:
    metadata:
      labels:
        app: service-rest
        version: ""
    spec:
      containers:
      - args:
        - java -jar /app/demo-docker-0.0.1-SNAPSHOT.jar
        command:
        - /bin/sh
        - -c
        image: lramirezq/book-app:0.1
        imagePullPolicy: IfNotPresent
        name: service-rest
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
      schedulerName: default-scheduler
